name: Secrets

on:
  workflow_dispatch:

jobs:
  testing_secrets:
    name: Testing secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: my first secret
        run: echo ${{ secrets.MY_SECRET }}
      - name: Decrypt a secret using a secret
        run: |
          mkdir -p $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.LARGE_SECRET_PASSPHRASE }}" \
            --output $HOME/secrets/larger_secret.txt secret.txt.gpg
          cat $HOME/secrets/larger_secret.txt
